name: Publish to NPM
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}
          fetch-depth: 0

      - name: 'cat package.json'
        run: cat ./package.json
      - name: 'Automated Version Bump'
        id: version-bump
        uses:  'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GIHUB_TOKEN }}
      - name: 'cat package.json'
        run: cat ./package.json
      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"

      - name: Set FOO
        run: git log --merges -1 | grep commit | awk -F' ' '{print $2}' >> idk.txt

      - uses: actions/github-script@v5
        id: get-comment
        with:
          script: |
            return github.rest.issues.getComment({
              comment_id: 'b73e7f26f8aba283585796a0d160f901d7fb3f41'
            }).body
          result-encoding: string

      - run: echo "${{ steps.get-comment.outputs.result }}"

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version-bump.outputs.newTag }}
          body: ${{ steps.get-comment.outputs.result }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
 
